### ISSUE TITLE
For 繁体中文使用者 ( SCIM to TCIM )

### ISSUE THREAD

**Issue by jaezh** [xiao99xiao/SCIMKiller#3]
@xiao99xiao  兄弟您好，我这边是台湾的使用者，输入法的关系也常常当机，发现繁体与简体输入法进程的区别应该只有一个字不同，因没有软件开发的经验，请问可以帮忙转换一个版本造福繁体中文使用者吗？ 感谢

测试过把以下网友分享的捷径命令句 [S] 换成 [T] 即可操作成功
ps aux | grep '[T]CIM_Extension' | awk '{print $2}' | xargs kill -9

**Comment by xiao99xiao** [comment]
好的这就安排。

**Comment by xiao99xiao** [comment]
请试一下 1.1 版本是否解决问题 https://github.com/xiao99xiao/SCIMKiller/releases/tag/1.1

**Comment by jaezh** [comment]
测试没问题，感谢兄弟🙌🏽💯
