### ISSUE TITLE
挺好的一个便捷app，希望可以build个基于更低版本MacOS可使用的。

### ISSUE THREAD

**Issue by wesselyang** [xiao99xiao/SCIMKiller#4]
现前这个（整合繁体输入过后其实可以更名为CIMKiller了，笑~）要求至少MacOS Ventura才能使用。
但其实这个也是历史久远的问题，无论Big Sur还是Monterey或者更前版本的MacOS其实一样存在中文输入圈圈停滞。
所以希望作者能build一个相对更低版本MacOS也能使用的版本并发布，让它的性更广也能照顾到更多老机型的mac吧，感谢~
比如Apple Silicon可以build对应的11.0起的，Intel的可以选择10.15（Catalina）之类的。：）

**Comment by xiao99xiao** [comment]
谢谢。[1.2版本](https://github.com/xiao99xiao/SCIMKiller/releases/tag/1.2)支持了macOS 13以下的版本。
